[package]
name = "login_ng"
version = "0.6.12"
edition = "2021"
license-file = "../LICENSE.md"

[dependencies]
users = "^0"
thiserror = "^2"
aes-gcm = "^0"
bcrypt = "^0"
hkdf = { version = "^0", features = [] }
sha2 = "^0"
xattr = "^1"
bytevec2 = "^0"
rs_sha512 = "^0"
